# Database configuration
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.show-sql=true
spring.flyway.baseline-on-migrate=true
spring.flyway.out-of-order=true
spring.flyway.url=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
spring.flyway.user=${DATABASE_ADMIN_USER:admin}
spring.flyway.password=${DATABASE_ADMIN_PASSWORD:password}
# Actuator configuration
management.endpoints.web.exposure.include=health
# Spring configuration
spring.application.name=orchealm-api
logging.level.root=${LOGGING_LEVEL:INFO}
# Authentication configuration
jwt.jwk-set-uri=${AUTH_JWK_SET_URI:}
jwt.issuer-uri=${AUTH_ISSUER_URI:}
jwt.claims.externalId=${AUTH_CLAIM_EXTERNAL_ID:sub}
jwt.claims.name=${AUTH_CLAIM_EXTERNAL_ID:name}
jwt.claims.email=${AUTH_CLAIM_EXTERNAL_ID:email}
## Https configuration
server.port=8443
server.ssl.key-store=${SSL_KEY_STORE}
server.ssl.key-store-password=${SSL_KEY_STORE_PASSWORD}
server.ssl.key-password=${SSL_KEY_PASSWORD}
# RLS configuration
super-admin.externalId=${SUPER_ADMIN_EXTERNAL_ID:}