CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE ROLE orchealm_api WITH LOGIN PASSWORD 'password';
GRANT USAGE ON SCHEMA public TO orchealm_api;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO orchealm_api;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO orchealm_api;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO orchealm_api;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE ON SEQUENCES TO orchealm_api;
